# Site Settings
baseurl: ""
url : "https://danimog.github.io"

# Blog Settings
theme_settings :
  title : Grape Theme rivisited
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/danielemoggia_cartoon.png
    username : Daniele Moggia
    description : My first jekyll theme forked from Grape Theme
    experience :
      - start : 2019-08-26
        end : 2020-01-01
        experience : Parco Nazionale delle Cinque Terre, Ufficio informatica
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
      - skill : PHP
        value : 70  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: danimog
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
